[package]
name = "deet"
version = "0.1.0"
authors = ["Phoenix Kahlo <kahlo.phoenix@gmail.com>"]
edition = "2018"

[dependencies]
cmd_lib = "0.7.8"
failure = "0.1.6"
unicode-segmentation = "1.6.0"
rand = "0.7.3"
regex = "1.3.3"